import { Header } from '@/components/header'
import { config } from '@/shared/config'
import { RootLayout } from '@/shared/layouts/root'
import { cn } from '@/shared/lib/utils'
import '@/shared/styles/globals.css'
import type { Metadata } from 'next'
import { Roboto, Roboto_Mono } from 'next/font/google'
import { PropsWithChildren } from 'react'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
})

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: config.NEXT_PUBLIC_APP_NAME,
  description: 'Generated by create next app',
}

export default function AppRootLayout({ children }: PropsWithChildren) {
  return (
    <RootLayout
      lang="en"
      className={cn(roboto.variable, robotoMono.variable)}
    >
      <main className="container mx-auto flex min-h-screen flex-col gap-4">
        <Header />
        {children}
      </main>
    </RootLayout>
  )
}
